

export const metadata = {
  title: 'Iframe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
      <link href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500&f[]=satoshi@500,400&display=swap" rel="stylesheet"></link>
      </head>
      <body style={{
    display: "flex",
    alignItems: "center",
    paddingTop: "60px",
    justifyContent: "center",
 }}>{children}</body>
      
    </html>
  )
}
